service: ci-cd

provider:
  name: aws
  stage: dev
  region: us-east-1
  stackName: Lambda-CI-CD
  runtime: nodejs14.x
  deploymentPrefix: serverless
  #s3:
    # Eventual additional properties in camel case
    #bucketOne:
      # Supported properties are the same ones as supported by CF resource for S3 bucket
      # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
      #name: my-custom-bucket-name
  deploymentBucket:
    name: my.lambda.deployment.bucket
    #blockPublicAccess: true
    #versioning: true
    #serverSideEncryption: AES256
    #sseKMSKeyId: arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
    # For server-side encryption with custom keys
    #sseCustomerAlgorithim: AES256
    #sseCustomerKey: string
    #sseCustomerKeyMD5: md5sum
  	
package:
  patterns:
    - src/**
    - handler.js
  individually: true
  artifact: my-lambda.zip
    
  
functions:
  hello:
    handler: src/handler.generateRandomNumber
